### ISSUE TITLE
Support not only literals

### ISSUE THREAD

**Issue by xoac** [NieDzejkob/enumflags2#20]
Hi,
Thanks for great crate!

I have noticed this problem: 
```
error: proc-macro derive panicked
   --> src/config.rs:139:54
    |
139 | #[derive(Debug, Clone, Copy, Serialize, Deserialize, BitFlags)]
    |                                                      ^^^^^^^^
    |
    = help: message: Only literals are supported
```

My struct
```rust
  #[derive(Debug, Clone, Copy, Serialize, Deserialize, BitFlags)]
  #[repr(u8)]
  pub enum ClassFieldBit {
      ClassZero = opendnp3::ClassField_CLASS_0,
      ClassOne = opendnp3::ClassField_CLASS_1,
      ClassTwo = opendnp3::ClassField_CLASS_2,
      ClassTree = opendnp3::ClassField_CLASS_3,
  }
```

 `opendnp3::ClassField_*` are defined as pub const u8. It should be supported

**Comment by NieDzejkob** [comment]
Hi. The reason for this requirement is that the macro attempts to verify that the bits don't overlap. I'll look into doing this with static assertions instead so that this also works.

As an immediate solution, if your `const`s are defined in the same crate, you can provide the literal values in the enum, and then define the constants in terms of it:

```
#[derive(Debug, Clone, Copy, Serialize, Deserialize, BitFlags)]
#[repr(u8)]
pub enum ClassFieldBit {
    ClassZero = 1 << 0,
    ClassOne = 1 << 1,
    ...
}

pub const ClassField_CLASS_0: u8 = ClassFieldBit::ClassZero as u8;
...
```

Though, if I may ask, what do you need the constants for?

**Comment by xoac** [comment]
There are generated with bindgen from c++. I just create a rust abstract over them.

**Comment by NieDzejkob** [comment]
I pushed a feature that, I think, solves this issue. Could you [add the crate as a git dependency](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories) and take a look? If it works for you, I'll probably make a release tomorrow.
